spring.application.name=backend-gestion-formation
spring.datasource.url=jdbc:mysql://localhost:3306/gestion-formation?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Fix for Hibernate Envers HHH015007 error - suppress harmless warning
logging.level.org.hibernate.metamodel.internal.MetadataContext=WARN

jwt.secret=9c2a9c472069a40038de07b2caa67beb4b897de79e885757a44f2ac1623d476f
jwt.expiration=86400

spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

server.port=8086
